# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd158d8d29a4c1f2786250c6d95d7f1e830625383e9001f798aeaea00a81b81decae72cbbeafa6eea76df6a67dc8ab36b36d5a723c3e3cbbb818c851e3427679

test:
  secret_key_base: 5edf662d172ef7a01e997d621a5bd1a04b71c741b4daced1d9562718a02f58ce7a16af9f7f9ee8c098690cfc4d5286fa67d556ffcd6b391589daf21b8db11256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
